export const loginConstants={
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER_REQUEST: "LOGIN_REQUEST",
  REGISTER_SUCCESS: "LOGIN_SUCCESS",
  REGISTER_FAILURE: "LOGIN_FAILURE",
};